import java.io.Serializable;
import java.util.HashMap;

public class Commit implements Serializable{
    private static final long serialVersionUID = 134252799453L;

    private String lastCommitId;
    private String commitId;
    private String treeId;
    private String message;
    private String time;

    // construct a commit object by lastCommitID, the treeID it stores, and the message
    // that user added when they use "java corgit commit -m"
    // last, the time is generated by the system when user commit
    public Commit(String lastCommitId, String commitId, String treeId, String message, String time) {
        this.lastCommitId = lastCommitId;
        this.commitId = commitId;
        this.treeId = treeId;
        this.message = message;
        this.time = time;
    }

    public String getLastCommitId() {
        return this.lastCommitId;
    }

    public String getTreeId() {
        return this.treeId;
    }

    
    public String getCommitId() {
        return commitId;
    }

    public String getMessage() {
        return message;
    }

    public String getTime() {
        return time;
    }

    // get all the index information of this time
    public HashMap<String, String> getCommitList() {
        HashMap<String, String> commitList = new HashMap<>();

        return commitList;
    } 

    // get commit object information by string to generate CommitID
    @Override
    public String toString() {
        return this.lastCommitId + this.treeId +this.message + this.time;
    }

    
}
