import java.io.Serializable;

public class Commit implements Serializable{
    private String lastCommitId;
    private String treeId;
    private String message;
    private String time;

    // construct a commit object by lastCommitID, the treeID it stores, and the message
    // that user added when they use "java corgit commit -m"
    // last, the time is generated by the system when user commit
    public Commit(String lastCommitId, String treeId, String message, String time) {
        this.lastCommitId = lastCommitId;
        this.treeId = treeId;
        this.message = message;
        this.time = time;
    }

    // get commit object information by string to generate CommitID
    @Override
    public String toString() {
        return this.lastCommitId + this.treeId +this.message + this.time;
    }

    
}
